<?php
$lang = array(

    "title.1" => "Dear Gamers",
    "title.2" => "Our studio is born from a passion for originality and a commitment to creating captivating gaming experiences. As an independent team, we thrive on innovation and the excitement of developing unique games that stand out.",
    "title.3" => "Every game we make is crafted with care, designed not just to entertain, but to inspire. We value your role in this journey and invite you to join us in shaping the future of gaming. Thank you for your support and for being an integral part of our creative adventure.",
    "title.4" => "Game on!",
    "title.5" => "The Uru Studios Team",

    "hauntedbricks.title" => "Haunted Bricks",
    "hauntedbricks.subtitle" => "A captivating puzzle game perfect for killing time, featuring animated characters inspired by classic animations and RPG adventures.",
    "hauntedbricks.apple" => "Apple Sore (August/2024)",
    "hauntedbricks.google" => "Google Play (August/2024)",
    "hauntedbricks.detail.title1" => "Thrilling Adventure",
    "hauntedbricks.detail.desc1" => "Join three young heroes as they take on a haunted house filled with mysterious brick monsters!",
    "hauntedbricks.detail.title2" => "Challenging Puzzles",
    "hauntedbricks.detail.desc2" => "Test your skills with complex puzzles that blend brick-breaking action with strategic RPG elements.",
    "hauntedbricks.detail.title3" => "Fun for All Ages",
    "hauntedbricks.detail.desc3" => "Designed to be enjoyed by puzzle lovers of all ages, perfect for a quick gaming session or an extended playtime.",

    "copyright" => "All rights reserved &copy; Uru Studios LTDA 2024 - <a href=\"mailto:contact@urustudios.com\">contact@urustudios.com</a>",

    "termsofservice" => "Terms of Services",
    "privacy" => "Privacy Policy",

    "privacy.version" => "Version 1.0 - 30th of April, 2024",
    "privacy.detail" => "<h2>1. Introduction</h2><p>Uru Studios ('we,' 'our,' or 'us') is committed to protecting your privacy. This Privacy Policy outlines how we collect, use, store, and share information when you use our games and services.</p><h2>2. Information We Collect</h2><p>We collect information such as your name, email address, and billing information, as well as telemetry data and game statistics. Additionally, we use AppLovin for marketing and analytics purposes.</p><h2>3. How We Use Your Information</h2><p>We use your information to provide, maintain, and improve our games and services, monitor gameplay, process transactions, and personalize experiences. We also use it for marketing and analytics through AppLovin.</p><h2>4. Sharing Information</h2><p>We may share your information with third parties only in the following situations: service providers, legal requirements, or business transfers. We also share data with AppLovin for marketing and telemetry purposes.</p><h2>5. Data Security</h2><p>We implement industry-standard measures to protect your data from unauthorized access, alteration, or loss. However, no transmission over the internet or electronic storage method is entirely secure.</p><h2>6. Children's Privacy</h2><p>Our games are not intended for children under 13 without parental consent. If we learn that we have collected data from a child under 13 without parental consent, we will take steps to delete that information.</p><h2>7. User Rights</h2><p>You have the right to access, correct, or delete your data. Contact us at privacy@urustudios.com to exercise these rights.</p><h2>8. Changes to This Policy</h2><p>We may update this Privacy Policy from time to time. Any changes will be posted on this page, and continued use of our services after the update constitutes acceptance of the new policy.</p><h2>9. Governing Law</h2><p>This Privacy Policy is governed by and construed in accordance with the laws of Brazil and the United States, depending on the user's location.</p>",

    "termsofservice.detail" => "<h2>1. Acceptance of Terms</h2><p>By downloading, installing, or using any game or service offered by Uru Studios, you agree to abide by these Terms of Service. If you do not agree, please refrain from using our games and services.</p><h2>2. Eligibility</h2><p>You must be at least 13 years old to use our services. If you are under 18 years old, you may use our services only with the involvement of a parent or guardian.</p><h2>3. Virtual Goods and Currency</h2><p>Our games may include virtual goods and currency available for purchase. These items have no real-world monetary value and cannot be exchanged outside the game. All sales of virtual goods and currency are final, and no refunds will be provided, except as required by law.</p><h2>4. User Conduct</h2><p>By using our services, you agree not to:</p><ul><li>Engage in cheating, hacking, or other unfair practices.</li><li>Harass, abuse, or harm other users.</li><li>Share, sell, or transfer your account or account details to another person.</li></ul><h2>6. Intellectual Property</h2><p>All content, including but not limited to graphics, gameplay mechanics, and music, are the intellectual property of Uru Studios or its licensors. You agree not to copy, distribute, or modify any part of our games or services without our explicit consent.</p><h2>7. Updates and Changes</h2><p>We may update or modify our games and services at any time without prior notice. We reserve the right to change these Terms of Service as necessary. Continued use of our services after changes constitutes acceptance of the new terms.</p><h2>8. Limitation of Liability</h2><p></p><ul><li>Uru Studios is not liable for any direct, indirect, incidental, or consequential damages arising from your use of our games or services.</li><li>Our total liability in connection with these Terms of Service is limited to the amount paid by you for our services.</li></ul><h2>9. Termination</h2><p>We reserve the right to terminate your access to our games or services for violating these Terms of Service or for any reason at our discretion.</p><h2>10. Governing Law</h2><p></p><ul><li>These Terms of Service are governed by and construed in accordance with the laws of Brazil and the United States, depending on the user's location.</li><li>For users residing in Brazil, any legal action or proceeding relating to these Terms of Service shall be brought exclusively in the courts of Brazil.</li><li>For users residing in the United States, any legal action or proceeding relating to these Terms of Service shall be brought exclusively in the courts of the United States.</li></ul>",
);
?>
