<?php
$lang = array(

    "title.1" => "Queridos Jogadores",
    "title.2" => "Nosso estúdio nasceu de uma paixão pela originalidade e um compromisso em criar experiências de jogo cativantes. Como uma equipe independente, prosperamos com a inovação e a emoção de desenvolver jogos únicos que se destacam.",
    "title.3" => "Cada jogo que fazemos é criado com cuidado, projetado não apenas para entreter, mas para inspirar. Valorizamos seu papel nesta jornada e convidamos você a se juntar a nós na formação do futuro dos jogos. Obrigado pelo seu apoio e por ser uma parte integral da nossa aventura criativa.",
    "title.4" => "Vamos jogar!",
    "title.5" => "A Equipe Uru Studios",

    "hauntedbricks.title" => "Haunted Bricks",
    "hauntedbricks.subtitle" => "Um jogo de quebra-cabeça cativante, perfeito para passar o tempo, com personagens animados inspirados em animações clássicas e aventuras de RPG.",
    "hauntedbricks.apple" => "Apple Store (Agosto/2024)",
    "hauntedbricks.google" => "Google Play (Agosto/2024)",
    "hauntedbricks.detail.title1" => "Aventura Emocionante",
    "hauntedbricks.detail.desc1" => "Junte-se a três jovens heróis enquanto eles enfrentam uma casa assombrada cheia de monstros de tijolos misteriosos!",
    "hauntedbricks.detail.title2" => "Quebra-Cabeças Desafiadores",
    "hauntedbricks.detail.desc2" => "Teste suas habilidades com quebra-cabeças complexos que combinam ação de quebra de tijolos com elementos estratégicos de RPG.",
    "hauntedbricks.detail.title3" => "Diversão para Todas as Idades",
    "hauntedbricks.detail.desc3" => "Desenhado para ser apreciado por amantes de quebra-cabeças de todas as idades, perfeito para uma sessão de jogo rápida ou um tempo de jogo prolongado.",

    "copyright" => "Todos os direitos reservados &copy; Uru Studios LTDA 2024 - <a href=\"mailto:contact@urustudios.com\">contact@urustudios.com</a>",

    "termsofservice" => "Termos de Serviço",
    "privacy" => "Política de Privacidade",

    "privacy.version" => "Versão 1.0 - 30 de Abril de 2024",
    "privacy.detail" => "<h2>1. Introdução</h2><p>A Uru Studios ('nós', 'nosso', ou 'nos') está comprometida em proteger sua privacidade. Esta Política de Privacidade descreve como coletamos, usamos, armazenamos e compartilhamos informações quando você usa nossos jogos e serviços.</p><h2>2. Informações que Coletamos</h2><p>Coletamos informações como seu nome, endereço de e-mail e informações de cobrança, bem como dados de telemetria e estatísticas de jogos. Além disso, usamos o AppLovin para fins de marketing e análises.</p><h2>3. Como Usamos Suas Informações</h2><p>Usamos suas informações para fornecer, manter e melhorar nossos jogos e serviços, monitorar o gameplay, processar transações e personalizar experiências. Também usamos para marketing e análises por meio do AppLovin.</p><h2>4. Compartilhamento de Informações</h2><p>Podemos compartilhar suas informações com terceiros apenas nas seguintes situações: prestadores de serviços, requisitos legais ou transferências de negócios. Também compartilhamos dados com o AppLovin para fins de marketing e telemetria.</p><h2>5. Segurança dos Dados</h2><p>Implementamos medidas padrão da indústria para proteger seus dados contra acesso não autorizado, alteração ou perda. No entanto, nenhuma transmissão pela internet ou método de armazenamento eletrônico é completamente seguro.</p><h2>6. Privacidade das Crianças</h2><p>Nossos jogos não são destinados a crianças menores de 13 anos sem o consentimento dos pais. Se soubermos que coletamos dados de uma criança menor de 13 anos sem o consentimento dos pais, tomaremos medidas para excluir essas informações.</p><h2>7. Direitos do Usuário</h2><p>Você tem o direito de acessar, corrigir ou excluir seus dados. Entre em contato conosco em privacy@urustudios.com para exercer esses direitos.</p><h2>8. Alterações a Esta Política</h2><p>Poderemos atualizar esta Política de Privacidade de tempos em tempos. Quaisquer alterações serão publicadas nesta página, e o uso contínuo de nossos serviços após a atualização constitui aceitação da nova política.</p><h2>9. Lei Aplicável</h2><p>Esta Política de Privacidade é regida e interpretada de acordo com as leis do Brasil e dos Estados Unidos, dependendo da localização do usuário.</p>",

    "termsofservice.detail" => "<h2>1. Aceitação dos Termos</h2><p>Ao baixar, instalar ou usar qualquer jogo ou serviço oferecido pela Uru Studios, você concorda em cumprir estes Termos de Serviço. Se você não concordar, por favor, não use nossos jogos e serviços.</p><h2>2. Elegibilidade</h2><p>Você deve ter pelo menos 13 anos para usar nossos serviços. Se você tiver menos de 18 anos, poderá usar nossos serviços apenas com o envolvimento de um pai ou responsável.</p><h2>3. Bens e Moeda Virtuais</h2><p>Nossos jogos podem incluir bens e moedas virtuais disponíveis para compra. Esses itens não têm valor monetário no mundo real e não podem ser trocados fora do jogo. Todas as vendas de bens e moedas virtuais são finais, e nenhum reembolso será fornecido, exceto conforme exigido por lei.</p><h2>4. Conduta do Usuário</h2><p>Ao usar nossos serviços, você concorda em não:</p><ul><li>Engajar-se em trapaça, hacking ou outras práticas desleais.</li><li>Assediar, abusar ou prejudicar outros usuários.</li><li>Compartilhar, vender ou transferir sua conta ou detalhes da conta para outra pessoa.</li></ul><h2>5. Propriedade Intelectual</h2><p>Todo o conteúdo, incluindo, mas não se limitando a gráficos, mecânicas de jogo e música, é propriedade intelectual da Uru Studios ou de seus licenciadores. Você concorda em não copiar, distribuir ou modificar qualquer parte de nossos jogos ou serviços sem nosso consentimento explícito.</p><h2>6. Atualizações e Alterações</h2><p>Poderemos atualizar ou modificar nossos jogos e serviços a qualquer momento, sem aviso prévio. Reservamo-nos o direito de alterar estes Termos de Serviço conforme necessário. O uso contínuo de nossos serviços após alterações constitui aceitação dos novos termos.</p><h2>7. Limitação de Responsabilidade</h2><p></p><ul><li>A Uru Studios não é responsável por quaisquer danos diretos, indiretos, incidentais ou consequenciais decorrentes do uso de nossos jogos ou serviços.</li><li>Nossa responsabilidade total em relação a estes Termos de Serviço é limitada ao valor pago por você por nossos serviços.</li></ul><h2>8. Rescisão</h2><p>Reservamo-nos o direito de encerrar seu acesso a nossos jogos ou serviços por violação destes Termos de Serviço ou por qualquer motivo, a nosso critério.</p><h2>9. Lei Aplicável</h2><p></p><ul><li>Estes Termos de Serviço são regidos e interpretados de acordo com as leis do Brasil e dos Estados Unidos, dependendo da localização do usuário.</li><li>Para usuários residentes no Brasil, qualquer ação ou processo legal relacionado a estes Termos de Serviço deverá ser movido exclusivamente nos tribunais do Brasil.</li><li>Para usuários residentes nos Estados Unidos, qualquer ação ou processo legal relacionado a estes Termos de Serviço deverá ser movido exclusivamente nos tribunais dos Estados Unidos.</li></ul>",
);
?>
